### ISSUE TITLE
drc not authenticating against private docker.io repos

### ISSUE THREAD

**Issue by Kroev** [gempesaw/node-clair-client#1]
Hi,

The issue I am facing is that we have private docker.io repos which require authentication in order to access them. I provided the clair-client constructor with credentials as described in the README. Even with these credentials provided the clair-client would still throw `UnauthorizedError`. I dug around a bit and I think I found the issue:

In lib/docker-registry.js
`this.isPublic = this.repoAndRef.index.name === 'docker.io';`
is used to determine whether authentication is required, see `get clientArgs()` in the same file:
```javascript
if (username && password && !isPublic) {
      debug('authorizing to docker registry as %o', username);
      return { username, password };
}
```

The core problem seems to be that checking if `index.name === 'docker.io'` does not seem to be sufficient to tell if authentication will be required. I also took a look at the `docker-registry-client` and I was not able to find a way to tell if a repo is private or not. 

The only solution for this that comes to my (unexperienced) mind is to allow the consumer to set the `isPublic` flag via `clair-client.analyze` (besides providing your own registry-client for docker.io which should be an overkill).

I will open a PR once I come to that.

Kroev

**Comment by gempesaw** [comment]
> The core problem seems to be that checking if index.name === 'docker.io' does not seem to be sufficient to tell if authentication will be required. 

oh, of course! this point makes a lot of sense. 

An `isPublic` flag seems quite appropriate.

**Comment by Kroev** [comment]
thank you for your answer, currently I am working on it, once I played around with it and find that it works as intended, I will open the PR
